con4gisDeliverFile:
    path: /con4gis/api/deliver
    defaults:
        _scope: frontend
        _controller: "con4gisCoreBundle:Api:deliver"
Con4gisCoreBundle:
    path: /con4gis/api/{_url_fragment}
    defaults:
        _scope: frontend
        _controller: "con4gisCoreBundle:Api:run"
    requirements:
        _url_fragment: .*

con4gisUploadImage:
    path: /con4gis/upload/image
    defaults:
        _scope: frontend
        _controller: "con4gisCoreBundle:Upload:imageUpload"

con4gisUploadFile:
    path: /con4gis/upload/file
    defaults:
        _scope: frontend
        _controller: "con4gisCoreBundle:Upload:fileUpload"