con4gisDeliverFile:
    path: /con4gis/api/deliver
    controller: con4gis\CoreBundle\Controller\ApiController::deliverAction
    methods: [GET]

Con4gisCoreBundle:
    path: /con4gis/api/{_url_fragment}
    controller: con4gis\CoreBundle\Controller\ApiController::runAction
    methods: [GET]
    requirements:
        _url_fragment: '.*'

con4gisUploadImage:
    path: /con4gis/upload/image
    controller: con4gis\CoreBundle\Controller\UploadController::imageUploadAction
    methods: [GET,POST]

con4gisUploadFile:
    path: /con4gis/upload/file
    controller: con4gis\CoreBundle\Controller\UploadController::fileUploadAction
    methods: [GET,POST]